table CompanyInfo
	lineageTag: 11a0275c-408a-4a85-8ae6-32ea54b3877b

	measure 'Current Company' = SELECTEDVALUE ( CompanyInfo[CompanyName], "No company selected" )
		lineageTag: 39943875-bace-4deb-9fa8-c1e348155edf

	column CompanyName
		dataType: string
		lineageTag: a72491ad-8b02-4f32-9532-af9a537cdebb
		summarizeBy: none
		sourceColumn: CompanyName

		annotation SummarizationSetBy = Automatic

	partition CompanyInfo = m
		mode: import
		source =
				let
				    CompanyName = Text.From(Company),
				    Output = #table({"CompanyName"}, {{CompanyName}})
				in
				    Output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

