table 'Dummy Budget'
	lineageTag: 8c635800-4d4e-4da8-9ec7-d895214ddbe8

	column budgetName
		dataType: string
		lineageTag: 44f695ba-bc00-457b-b79a-196b70320bd4
		summarizeBy: none
		sourceColumn: budgetName

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: int64
		formatString: 0
		lineageTag: 97b1bbbb-851e-4629-b512-3db28760d857
		summarizeBy: none
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

	column id
		dataType: int64
		formatString: 0
		lineageTag: dd548e63-9f23-4fd6-a498-dec655c7ff88
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column ooooooo
		dataType: string
		lineageTag: e7bc8e69-9c7f-4b19-b881-83445127f5d6
		summarizeBy: none
		sourceColumn: ooooooo

		annotation SummarizationSetBy = Automatic

	column globalDimension1Code
		dataType: string
		lineageTag: 5860e4db-fa5a-4289-8d0b-6ed1f10a2925
		summarizeBy: none
		sourceColumn: globalDimension1Code

		annotation SummarizationSetBy = Automatic

	column globalDimension2Code
		dataType: string
		lineageTag: 06d467b8-c2ea-4948-ba6a-1544d22afed8
		summarizeBy: none
		sourceColumn: globalDimension2Code

		annotation SummarizationSetBy = Automatic

	column budgetDimension1Code
		dataType: string
		lineageTag: 506e9834-245d-41f0-a7d6-9df750b531a4
		summarizeBy: none
		sourceColumn: budgetDimension1Code

		annotation SummarizationSetBy = Automatic

	column budgetDimension2Code
		dataType: string
		lineageTag: c22a9b14-ecfb-40f3-a500-fd814aa2e37f
		summarizeBy: none
		sourceColumn: budgetDimension2Code

		annotation SummarizationSetBy = Automatic

	column budgetDimension3Code
		dataType: string
		lineageTag: 41693a9a-1dab-4863-8f72-9626dc2d7454
		summarizeBy: none
		sourceColumn: budgetDimension3Code

		annotation SummarizationSetBy = Automatic

	column budgetDimension4Code
		dataType: string
		lineageTag: 0929c0b3-8ac5-453f-9e5d-6bcdae346f7f
		summarizeBy: none
		sourceColumn: budgetDimension4Code

		annotation SummarizationSetBy = Automatic

	partition 'Dummy Budget' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WUghOzUlNLlFIKk1JTy1R0lEyAGJDKI6AAexsJFHsTCAnNhYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [budgetName = _t, amount = _t, id = _t, ooooooo = _t, globalDimension1Code = _t, globalDimension2Code = _t, budgetDimension1Code = _t, budgetDimension2Code = _t, budgetDimension3Code = _t, budgetDimension4Code = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"budgetName", type text}, {"amount", Int64.Type}, {"id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

