#!/usr/bin/env python3
import argparse
import csv
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

from hdbcli import dbapi


DATASETS = [
    "bp_master",
    "item_master",
    "ar_open_items",
    "ap_open_items",
    "journal_entries",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export SAP B1 HANA snapshots (read-only).")
    parser.add_argument("--config", required=True, help="Path to config.json")
    parser.add_argument("--snapshot-date", required=True, help="Snapshot date (YYYY-MM-DD)")
    parser.add_argument(
        "--format",
        choices=["parquet", "csv"],
        default="parquet",
        help="Output file format",
    )
    return parser.parse_args()


def load_config(path: Path) -> Dict:
    return json.loads(path.read_text(encoding="utf-8"))


def ensure_date_yyyy_mm_dd(value: str) -> None:
    datetime.strptime(value, "%Y-%m-%d")


def read_sql(query_dir: Path, dataset: str, schema: str, company_code: str) -> str:
    sql_path = query_dir / f"{dataset}.sql"
    template = sql_path.read_text(encoding="utf-8")
    return template.format(schema=schema, company_code=company_code)


def fetch_rows(
    conn: dbapi.Connection,
    sql: str,
) -> Tuple[List[str], List[Tuple]]:
    cur = conn.cursor()
    cur.execute(sql)
    rows = cur.fetchall()
    columns = [d[0] for d in cur.description]
    return columns, rows


def rows_to_dicts(columns: Sequence[str], rows: Sequence[Tuple]) -> List[Dict]:
    return [{columns[i]: row[i] for i in range(len(columns))} for row in rows]


def write_csv(path: Path, columns: Sequence[str], rows: Sequence[Tuple]) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(columns)
        writer.writerows(rows)


def write_parquet(path: Path, records: List[Dict]) -> None:
    try:
        import pyarrow as pa
        import pyarrow.parquet as pq
    except ImportError as exc:
        raise RuntimeError(
            "Parquet requested but pyarrow is not installed. Install with: pip install pyarrow"
        ) from exc

    table = pa.Table.from_pylist(records)
    pq.write_table(table, str(path))


def write_manifest(snapshot_dir: Path, snapshot_date: str, files: List[str]) -> None:
    manifest = snapshot_dir / "manifest.md"
    now = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    body = [
        "# Snapshot Manifest",
        "",
        f"- Snapshot date: `{snapshot_date}`",
        "- Snapshot owner: `SAP Export Pipeline`",
        "- Source model/workspace: `SAP B1 HANA (read-only)`",
        "- Schema version: `v1`",
        f"- Export run timestamp: `{now}`",
        "",
        "## Included datasets",
        "",
    ]
    body.extend([f"- `{name}`" for name in files])
    body.extend(["", "## Notes", "", "- Generated by export pipeline script."])
    manifest.write_text("\n".join(body) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    ensure_date_yyyy_mm_dd(args.snapshot_date)

    config = load_config(Path(args.config))
    hana = config["hana"]
    companies = config["companies"]
    base_dir = Path(config["output"]["base_dir"])
    schema_version = config["output"]["schema_version"]

    user = os.environ.get(hana["user_env"], "")
    password = os.environ.get(hana["password_env"], "")
    if not user or not password:
        raise RuntimeError(
            f"Missing credentials in env vars: {hana['user_env']} / {hana['password_env']}"
        )

    snapshot_dir = base_dir / args.snapshot_date
    snapshot_dir.mkdir(parents=True, exist_ok=True)

    script_dir = Path(__file__).resolve().parent
    query_dir = script_dir.parent / "queries"

    conn = dbapi.connect(
        address=hana["host"],
        port=int(hana["port"]),
        user=user,
        password=password,
    )

    written_files: List[str] = []

    try:
        for dataset in DATASETS:
            merged_columns: List[str] = []
            merged_rows: List[Tuple] = []

            for company in companies:
                sql = read_sql(
                    query_dir=query_dir,
                    dataset=dataset,
                    schema=company["schema"],
                    company_code=company["company_code"],
                )
                cols, rows = fetch_rows(conn, sql)
                if not merged_columns:
                    merged_columns = cols
                merged_rows.extend(rows)

            base_name = f"{dataset}__{args.snapshot_date}__{schema_version}"
            if args.format == "csv":
                file_name = f"{base_name}.csv"
                out_path = snapshot_dir / file_name
                write_csv(out_path, merged_columns, merged_rows)
            else:
                file_name = f"{base_name}.parquet"
                out_path = snapshot_dir / file_name
                records = rows_to_dicts(merged_columns, merged_rows)
                write_parquet(out_path, records)

            written_files.append(file_name)
            print(f"Wrote {file_name} with {len(merged_rows)} rows")
    finally:
        conn.close()

    write_manifest(snapshot_dir, args.snapshot_date, written_files)
    print(f"Snapshot complete: {snapshot_dir}")


if __name__ == "__main__":
    main()
