table Period
	lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0001

	measure SelectedKPI = MIN ( 'Period'[KPI_ID] )
		formatString: 0
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0002

	column KPI
		dataType: string
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0003
		summarizeBy: none
		sourceColumn: KPI
		sortByColumn: KPI_ID

		annotation SummarizationSetBy = Automatic

	column KPI_ID
		dataType: int64
		formatString: 0
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0004
		summarizeBy: none
		sourceColumn: KPI_ID

		annotation SummarizationSetBy = Automatic

	partition Period = calculated
		mode: import
		source =
				
				DATATABLE (
				    "KPI", STRING,
				    "KPI_ID", INTEGER,
				    {
				        { "This week", 1 },
				        { "This month", 2 },
				        { "This quarter", 3 },
				        { "This fiscal year", 4 },
				        { "This calendar year", 5 }
				    }
				)

	annotation PBI_Id = 4f1c4f8e3cc34d189a8c3f2e189a0001
