table _Measures
	lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa001

	measure 'Total On Hand' = SUM ( Fact_WarehouseStock[OnHand] )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa002

	measure 'Total Committed' = SUM ( Fact_WarehouseStock[IsCommited] )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa003

	measure 'Total Available' = [Total On Hand] - [Total Committed]
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa004

	measure 'Total On Order' = SUM ( Fact_WarehouseStock[OnOrder] )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa005

	measure 'Distinct SKUs' = DISTINCTCOUNT ( Fact_WarehouseStock[ItemCode] )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa006

	measure 'In-Stock SKUs' =
			CALCULATE (
			    DISTINCTCOUNT ( Fact_WarehouseStock[ItemCode] ),
			    Fact_WarehouseStock[OnHand] > 0
			)
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa007

	measure 'Total SKUs' = COUNTROWS ( Dim_Item )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa008

	measure 'Stock Value' =
			SUMX (
			    Fact_WarehouseStock,
			    Fact_WarehouseStock[OnHand] *
			        IF (
			            RELATED ( Dim_Item[AvgPrice] ) > 0,
			            RELATED ( Dim_Item[AvgPrice] ),
			            RELATED ( Dim_Item[LastPurPrc] )
			        )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa009

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Inbound Qty' = SUM ( Fact_StockMovement[InQty] )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa010

	measure 'Outbound Qty' = SUM ( Fact_StockMovement[OutQty] )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa011

	measure 'Net Movement' = [Inbound Qty] - [Outbound Qty]
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa012

	measure 'Movement Count' = COUNTROWS ( Fact_StockMovement )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa013

	measure 'Transfer Qty' = SUM ( Fact_Transfer[Quantity] )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa014

	measure 'Transfer Count' = DISTINCTCOUNT ( Fact_Transfer[DocEntry] )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa015

	measure 'Delivery Count' = DISTINCTCOUNT ( Fact_Delivery[DocEntry] )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa016

	measure 'Delivery Qty' = SUM ( Fact_Delivery[Quantity] )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa017

	measure 'Delivery Value' = SUM ( Fact_Delivery[LineTotal] )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa018

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'PO Count' = DISTINCTCOUNT ( Fact_PurchaseOrder[DocEntry] )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa019

	measure 'PO Qty' = SUM ( Fact_PurchaseOrder[Quantity] )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa020

	measure 'PO Value' = SUM ( Fact_PurchaseOrder[LineTotal] )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa021

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Open PO Count' =
			VAR _result =
			    CALCULATE (
			        DISTINCTCOUNT ( Fact_PurchaseOrder[DocEntry] ),
			        Fact_PurchaseOrder[DocStatus] = "O"
			    )
			RETURN
			    IF ( ISBLANK ( _result ), 0, _result )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa022

	measure 'GR Count' = DISTINCTCOUNT ( Fact_GoodsReceipt[DocEntry] )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa023

	measure 'GR Qty' = SUM ( Fact_GoodsReceipt[Quantity] )
		formatString: #,0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaa024

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

