table customerLedgerEntries
	lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0601

	measure TotalOutstanding_AR =
			
			SUMX ( FILTER ( 'customerLedgerEntries', 'customerLedgerEntries'[open] = 1 ), 'customerLedgerEntries'[remainingAmount] )
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0602

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalOverdue_AR =
			
			SUMX (
			    FILTER ( 'customerLedgerEntries', 'customerLedgerEntries'[open] = 1 && 'customerLedgerEntries'[dueDate] < TODAY () ),
			    'customerLedgerEntries'[remainingAmount]
			)
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0603

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PercentageOverdue =
			
			IF ( [TotalOutstanding_AR] = 0, "--", FORMAT ( DIVIDE ( [TotalOverdue_AR], [TotalOutstanding_AR] ), "0%" ) )
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0604

	measure AccountReceivable_outstanding = [TotalOutstanding_AR]
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0605

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AR_CountOfInvoices = DISTINCTCOUNT ( 'customerLedgerEntries'[documentNo] )
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0606

	measure AR_totalPayable_funnel = [TotalOutstanding_AR]
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0607

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AR_totalReceivable_funnel = [AR_totalPayable_funnel]
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0626

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AR_notYetDue_funnel =
			
			SUMX (
			    FILTER ( 'customerLedgerEntries', 'customerLedgerEntries'[open] = 1 && 'customerLedgerEntries'[dueDate] >= TODAY () ),
			    'customerLedgerEntries'[remainingAmount]
			)
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0608

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AR_overdue_funnel = [TotalOverdue_AR]
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0609

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AR_InvoiceStatusPercent_Open =
			
			DIVIDE (
			    COUNTROWS ( FILTER ( 'customerLedgerEntries', 'customerLedgerEntries'[open] = 1 && 'customerLedgerEntries'[dueDate] >= TODAY () ) ),
			    COUNTROWS ( 'customerLedgerEntries' )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0610

	measure AR_InvoiceStatusPercent_Overdue =
			
			DIVIDE (
			    COUNTROWS ( FILTER ( 'customerLedgerEntries', 'customerLedgerEntries'[open] = 1 && 'customerLedgerEntries'[dueDate] < TODAY () ) ),
			    COUNTROWS ( 'customerLedgerEntries' )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0611

	measure AR_InvoiceStatusPercent_Paid =
			
			DIVIDE (
			    COUNTROWS ( FILTER ( 'customerLedgerEntries', 'customerLedgerEntries'[open] = 0 || 'customerLedgerEntries'[remainingAmount] = 0 ) ),
			    COUNTROWS ( 'customerLedgerEntries' )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0612

	measure AccountReceivables_ageingReport_new =
			
			VAR Bucket = SELECTEDVALUE ( 'DueCategorySortTable_AR'[DueCategory] )
			RETURN
			    SWITCH (
			        Bucket,
			        "Overdue >90 days", SUMX ( FILTER ( 'customerLedgerEntries', 'customerLedgerEntries'[open] = 1 && 'customerLedgerEntries'[dueDate] < TODAY () - 90 ), 'customerLedgerEntries'[remainingAmount] ),
			        "Overdue 61-90 days", SUMX ( FILTER ( 'customerLedgerEntries', 'customerLedgerEntries'[open] = 1 && 'customerLedgerEntries'[dueDate] >= TODAY () - 90 && 'customerLedgerEntries'[dueDate] < TODAY () - 60 ), 'customerLedgerEntries'[remainingAmount] ),
			        "Overdue 31-60 days", SUMX ( FILTER ( 'customerLedgerEntries', 'customerLedgerEntries'[open] = 1 && 'customerLedgerEntries'[dueDate] >= TODAY () - 60 && 'customerLedgerEntries'[dueDate] < TODAY () - 30 ), 'customerLedgerEntries'[remainingAmount] ),
			        "Overdue 1-30 days", SUMX ( FILTER ( 'customerLedgerEntries', 'customerLedgerEntries'[open] = 1 && 'customerLedgerEntries'[dueDate] >= TODAY () - 30 && 'customerLedgerEntries'[dueDate] < TODAY () ), 'customerLedgerEntries'[remainingAmount] ),
			        "Due next 30 days", SUMX ( FILTER ( 'customerLedgerEntries', 'customerLedgerEntries'[open] = 1 && 'customerLedgerEntries'[dueDate] >= TODAY () && 'customerLedgerEntries'[dueDate] < TODAY () + 30 ), 'customerLedgerEntries'[remainingAmount] ),
			        "Still on time", SUMX ( FILTER ( 'customerLedgerEntries', 'customerLedgerEntries'[open] = 1 && 'customerLedgerEntries'[dueDate] >= TODAY () + 30 ), 'customerLedgerEntries'[remainingAmount] ),
			        [TotalOverdue_AR]
			    )
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0613

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalCreditSales =
			
			SUMX (
			    FILTER (
			        'customerLedgerEntries',
			        'customerLedgerEntries'[paymentMethodCode] <> "CASH"
			            && 'customerLedgerEntries'[postingDate] >= TODAY () - 365
			            && 'customerLedgerEntries'[postingDate] <= TODAY ()
			    ),
			    'customerLedgerEntries'[amount]
			)
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0614

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DSO =
			
			IF ( [TotalCreditSales] = 0, "--", FORMAT ( DIVIDE ( [TotalOutstanding_AR], [TotalCreditSales] ) * 365, "0" ) )
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0615

	measure RTO =
			
			IF ( [TotalOutstanding_AR] = 0, "--", FORMAT ( DIVIDE ( [TotalCreditSales], [TotalOutstanding_AR] ), "0.0" ) )
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0616

	column postingDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0617
		summarizeBy: none
		sourceColumn: postingDate

		annotation SummarizationSetBy = Automatic

	column dueDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0618
		summarizeBy: none
		sourceColumn: dueDate

		annotation SummarizationSetBy = Automatic

	column documentNo
		dataType: int64
		formatString: 0
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0619
		summarizeBy: none
		sourceColumn: documentNo

		annotation SummarizationSetBy = Automatic

	column customerCode
		dataType: string
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0620
		summarizeBy: none
		sourceColumn: customerCode

		annotation SummarizationSetBy = Automatic

	column customerName
		dataType: string
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0621
		summarizeBy: none
		sourceColumn: customerName

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0622
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

	column remainingAmount
		dataType: double
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0623
		summarizeBy: sum
		sourceColumn: remainingAmount

		annotation SummarizationSetBy = Automatic

	column open
		dataType: int64
		formatString: 0
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0624
		summarizeBy: none
		sourceColumn: open

		annotation SummarizationSetBy = Automatic

	column paymentMethodCode
		dataType: string
		lineageTag: 4f1c4f8e-3cc3-4d18-9a8c-3f2e189a0625
		summarizeBy: none
		sourceColumn: paymentMethodCode

		annotation SummarizationSetBy = Automatic

	partition customerLedgerEntries = m
		mode: import
		source =
				let
				    Source = Odbc.Query("dsn=HANA_B1", "SELECT#(lf)    T0.""DocDate"" AS ""postingDate"",#(lf)    T0.""DocDueDate"" AS ""dueDate"",#(lf)    T0.""DocNum"" AS ""documentNo"",#(lf)    T0.""CardCode"" AS ""customerCode"",#(lf)    T0.""CardName"" AS ""customerName"",#(lf)    COALESCE(T0.""DocTotal"", 0) AS ""amount"",#(lf)    COALESCE(T0.""DocTotal"", 0) - COALESCE(T0.""PaidToDate"", 0) AS ""remainingAmount"",#(lf)    CASE WHEN T0.""DocStatus"" = 'O' THEN 1 ELSE 0 END AS ""open"",#(lf)    COALESCE(T0.""PeyMethod"", '') AS ""paymentMethodCode""#(lf)FROM ""CANON"".""OINV"" T0#(lf)UNION ALL#(lf)SELECT#(lf)    T0.""DocDate"" AS ""postingDate"",#(lf)    T0.""DocDueDate"" AS ""dueDate"",#(lf)    T0.""DocNum"" AS ""documentNo"",#(lf)    T0.""CardCode"" AS ""customerCode"",#(lf)    T0.""CardName"" AS ""customerName"",#(lf)    COALESCE(T0.""DocTotal"", 0) * -1 AS ""amount"",#(lf)    (COALESCE(T0.""DocTotal"", 0) - COALESCE(T0.""PaidToDate"", 0)) * -1 AS ""remainingAmount"",#(lf)    CASE WHEN T0.""DocStatus"" = 'O' THEN 1 ELSE 0 END AS ""open"",#(lf)    COALESCE(T0.""PeyMethod"", '') AS ""paymentMethodCode""#(lf)FROM ""CANON"".""ORIN"" T0;")
				in
				    Source

	annotation PBI_ResultType = Table

